name: Try to Create OCI VM

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh
          bash install.sh --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Prepare OCI Config & Key
        run: |
          mkdir -p ~/.oci
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > ~/.oci/key.pem
          chmod 600 ~/.oci/key.pem

          cat <<EOF > ~/.oci/config
          [DEFAULT]
          user=${{ secrets.OCI_CLI_USER }}
          fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_CLI_TENANCY }}
          region=${{ secrets.OCI_CLI_REGION }}
          key_file=~/.oci/key.pem
          EOF
          # 修复：添加config文件权限
          chmod 600 ~/.oci/config
          
          # 修复：修复文件权限警告
          oci setup repair-file-permissions --file ~/.oci/config
          
      - name: Launch VM
        env:
          SSH_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          
          # 修复：添加 --wait-for-state 参数并使用 --debug 获取详细错误信息
          oci compute instance launch \
            --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }} \
            --availability-domain ${{ secrets.AD_NAME }} \
            --shape VM.Standard.A1.Flex \
            --shape-config: '{"ocpus": 1, "memory_in_gbs": 6}'
            --image-id ${{ secrets.IMAGE_ID }} \
            --subnet-id ${{ secrets.OCI_SUBNET_ID }} \
            --assign-public-ip true \
            --ssh-authorized-keys-file ~/.ssh/id_rsa.pub \
            --display-name "GitHub-Actions-ARM" \
            --wait-for-state RUNNING \
            --wait-interval-seconds 30 \
            --debug
